### ISSUE TITLE
Event's do not load

### ISSUE THREAD

**Issue by sophie-h** [emmanueltouzery/cigale#7]
Started it from terminal and this seems to be the problem

```sh
$ flatpak run com.github.emmanueltouzery.cigale 
thread '<unnamed>' panicked at 'no group at index '1'', /run/build/cigale/cargo/vendor/regex-1.3.7/src/re_unicode.rs:1021:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Removed all my git event sources and the panic is gone and other sources are loading again.

**Comment by sophie-h** [comment]
Can't reproduce this with a fresh clone of the source git repo. So maybe it's not too big of an issue :laughing:

**Comment by emmanueltouzery** [comment]
So it fails only when run as a flatpak? Interesting. It seems some regex is failing. Can you run:

flatpak run com.github.emmanueltouzery.cigale --env=RUST_BACKTRACE=1

**Comment by sophie-h** [comment]
> So it fails only when run as a flatpak?

No, sorry. I meant a fresh clone of the git repo that I have added as "event source" in Cigale. So there is only one strange git repo on my disk that is causing this issue if added as event source.

The backtrace isn't looking that helpful to me.

```sh
$ flatpak run --env=RUST_BACKTRACE=1 com.github.emmanueltouzery.cigale
thread '<unnamed>' panicked at 'no group at index '1'', /run/build/cigale/cargo/vendor/regex-1.3.7/src/re_unicode.rs:1021:32
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: clone
```

**Comment by emmanueltouzery** [comment]
haha the backtrace is really awesome. ok, i looked at the source of the git event provider again.. sure enough, i apply some regex on the git repo origin, to try to find out if it's a github or gitlab repo (in which case I can offer a link in the cigale GUI to open the commit in the browser). Obviously something is wrong with that regex, i'll check it out.

I don't think it's really necessary, but if it doesn't bother you at all, maybe it'll help me if you give me the origin url for that problematic repo:

```
git remote -v
```

but again... I think I can do without if it's any trouble at all for you.

**Comment by emmanueltouzery** [comment]
reproduced it in a unit test:

```rust
#[test]
fn it_properly_parses_http_remote_github_url() {
    assert_eq!(
        Some("https://github.com/emmanueltouzery/cigale/commit/".to_string()),
        Git::get_commit_display_url_github("https://github.com/emmanueltouzery/cigale.git")
            .unwrap()
    );
}
```
